name: Tweet Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行（UTC時間）

jobs:
  tweet:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # リポジトリをクローン

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 使用するPythonのバージョン

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # 依存関係をインストール

    - name: Run the Python script
      run: |
        python meigen-bot.py  # スクリプトを実行
